# Welcome to Jekyll!
title: BlueMarmle
email: bluemamrmle@163.com
description:  # this means to ignore newlines until "baseurl:"
baseurl: / # the subpath of your site, e.g. /blog
url: https://www.bluemarmle.com/ # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb

# Build settings
markdown: kramdown
theme: minima


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
